Book A Doctors Appointment(Back-End)
Haywayaheadshot/book-an-appointment pull request #21
Opened 2023-03-15 15:29 UTC by Haywayaheadshot

# What?

This is the back-end of an app that allows users to book doctor appointments. It was connected to [this](https://github.com/Haywayaheadshot/book-an-appointment-front-end) front-end repo.

# Why?

So the application can be easily maintained.

# How?
  - My coding partners and I;
      > Installed rails
      > Installed Ruby On Rails linters without the stylelint.
      > initialized the project backend with rails.
      > Created the backend to receive the frontend's signup data for user registration.
      > Updated the Cors file to include all methods
      > Added a table to handle username uniqueness so no two people can use the same username.
      > Created the User Login Page
      > Created the Api for the Login page
      > Created a doctors table.
      > Populated the doctors table.
      > Created a reservations table.
      > Created an API sending out all doctors.
      > Created an API to create and display reservations
      > Remove the views
      > Cleaned the code
      > Fix the routes
      > Removed commented lines in API controllers
      > Wrote test for the app

### Colaborators on this project are;
@eng-mohamed-eldeeb 
@Kelvin-Ben 
@asnganje 
@Haywayaheadshot

2023-03-15 17:18 UTC, Meltrust requested changes
Hi @Haywayaheadshot,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  Nice code organization ✔️ 
-  API is working well✔️ 
-  Good readme ✔️ 
-  Beautiful frontend ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-03-15 17:18 UTC, Meltrust commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [x] This is just a placeholder for you to create and include a license file.  Kindly remove this note, as it's meant just for you. 👍

2023-03-15 17:18 UTC, Meltrust commented on README.md
> +[$ rails s]
- [x] Kindly, include in your instructions the required db commands that your users will need to run your backend app: `rails db:create, rails db:migrate, rails db:seed`. 👍   

- [x] I couldn't find any documentation for your API.  If it exists, kindly add instructions on your readme about how to access it, as this is a requirement for a team of 4 people.  If it does not exist yet, kindly implement it.👍

2023-03-15 17:18 UTC, Meltrust commented on README.md
> +  bin/rails test test/models/article_test.rb
- [x] This command is not working on my end.  Also, I tried to run the tests found under the "test" folder but gave me errors.   Rspec worked fine (all 10 tests passed).

![image](https://user-images.githubusercontent.com/57421823/225383344-cf844ab3-5f00-4822-9acb-8c0577041437.png)

Kindly, correct this command in your instructions so all your tests pass.

- [ ] OPTIONAL:  If you are not using the "test" folder, kindly remove it

2023-03-15 17:36 UTC, Haywayaheadshot commented
@Meltrust Thank you for reviewing our project. We will work on the changes asap

2023-03-16 02:52 UTC, Meltrust approved these changes
_Note:  This review outcome applies **only** to the backend project.  Kindly, go to the frontend [PR](https://github.com/Haywayaheadshot/book-an-appointment-front-end/pull/17) to see the review comments for that project._

#### Hi @Haywayaheadshot,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Readme has been vastly improved✔️ 
- Documentation has been added, and it looks great✔️ 
- Tests instructions have been updated✔️
- Awesome job ✔️  



Cheers and Happy coding!👏👏👏


------

2023-03-16 03:10 UTC, Haywayaheadshot commented
@Meltrust Thank you for your kind words. Also, thank you for reviewing our project. It has been a great journey indeed. 🙏🏾🙏🏾

2023-03-17 14:13 UTC, merged

2023-04-21 04:56 UTC, Meltrust commented on app/controllers/api/doctors_controller.rb
> +        @doctors_reservations.destroy_all # deletes all records linking the doctor and reservations
- [ ] Kindly, remove this old commented code in order to improve the repo's cleanliness. 👍